### ISSUE TITLE
jar given to class is busted

### ISSUE THREAD

**Issue by tmsimont** [Wmaxlees/prefetch#77]
Hey guys,

We are reviewing your project and it looks like the prefetch.jar and the current git repo is broken.

The App class looks for `test_ptr.s` and there is no such file in your [resources folder](https://github.com/Wmaxlees/prefetch/tree/develop/resources)

This results in a null pointer exception.

**Comment by Wmaxlees** [comment]
Thanks for letting us know Trevor. Should be up now.
